-- Usamos "GENERATED BY DEFAULT AS IDENTITY" que es el estándar de SQL
-- para columnas auto-incrementales y es compatible con PostgreSQL.
CREATE TABLE usuarios_master (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 username VARCHAR(255) NOT NULL UNIQUE,
                                 password VARCHAR(255) NOT NULL,
                                 role VARCHAR(50) NOT NULL
);

INSERT INTO usuarios_master (username, password, role) VALUES ('superadmin', '$2a$10$3z3w.N3B.y5pZ4.5.3nJ9e/G/5c.9KjY6.YjV.d/5e.7X.z/d.u', 'SUPER_ADMIN');