app:
  datasource:
    master:
      url: jdbc:postgresql://localhost:59908/ferreteria_master
      username: admin
      password: password
      driver-class-name: org.postgresql.Driver

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/master
    baseline-on-migrate: true
    # --- PASO 1: AÑADIR ESTA LÍNEA TEMPORALMENTE ---
    # Esta opción le dice a Flyway que actualice el checksum (la firma)
    # de la migración que ha fallado.
    repair: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true