app:
  datasource:
    master:
      url: jdbc:postgresql://localhost:59908/ferreteria_master
      username: admin
      password: password
      driver-class-name: org.postgresql.Driver

spring:
  # Habilitamos Flyway y lo apuntamos a las migraciones de la BD Maestra
  flyway:
    enabled: true
    locations: classpath:db/migration/master
    baseline-on-migrate: true
  # Quitamos toda la configuración de JPA de aquí, porque la controlamos en las clases Java
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true